system: 
  ip: 127.0.0.1
  port: 8888
  env: dev
  gin_mode: debug
log: 
  app: blogx_server
  dir: log
jwt: 
  expire: 3
  secret: xxx
  issuer: lichun
redis:
  addr: 127.0.0.1:6379
  passwd: 
  db: 1
ai: 
  enable: false
  secretKey: jgojgoajgopgjopgjpaog
  nickname: 小猪
  avatar: /xxx/xxx
db:
  user: lichun
  password: 123456
  host: 127.0.0.1
  port: 3306
  dbname: blogx
  debug: false # 打印全部日志
db1: # 可为空
  user: lichun
  password: 123456
  host: 127.0.0.1
  port: 3306
  dbname: blogx
  debug: false # 打印全部日志